### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by juliandavid333** [Beanow/jaegertracing-example-android#1]
body-parser deprecated undefined extended: provide extended option app.js:12:17
Jaeger Mediator server listening on port 3000
** Use the /batch endpoint to report your Jaeger Spans to a Jaeger collector. **
** The collector and agent can be configured in configuration.json **
** To see an example of the accepted structure for reporting spans, make a GET to /sampleBatch **
TypeError: Cannot read property 'length' of undefined
    at prunedSpans (/Users/juliandavid/Downloads/jaeger-swift-master/Example/jaegerMediator/Sender/UDPSender.js:31:31)
    at Object.reportBatch (/Users/juliandavid/Downloads/jaeger-swift-master/Example/jaegerMediator/Sender/UDPSender.js:66:26)
    at /Users/juliandavid/Downloads/jaeger-swift-master/Example/jaegerMediator/app.js:26:10
    at Layer.handle [as handle_request] (/Users/juliandavid/Downloads/jaeger-swift-master/Example/jaegerMediator/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/juliandavid/Downloads/jaeger-swift-master/Example/jaegerMediator/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/juliandavid/Downloads/jaeger-swift-master/Example/jaegerMediator/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/juliandavid/Downloads/jaeger-swift-master/Example/jaegerMediator/node_modules/express/lib/router/layer.js:95:5)
    at /Users/juliandavid/Downloads/jaeger-swift-master/Example/jaegerMediator/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/juliandavid/Downloads/jaeger-swift-master/Example/jaegerMediator/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/juliandavid/Downloads/jaeger-swift-master/Example/jaegerMediator/node_modules/express/lib/router/index.js:275:10)

**Comment by Beanow** [comment]
Hi @juliandavid333

Unfortunately I haven't continued the project that I was researching Jaegertracing on Android for.
So I haven't maintained this example in the past 3 years, or know if the issues I had have been solved.

I think it's best if you look around the Jaeger side to see what the current state is.
Some issues that I know about:
- https://github.com/jaegertracing/jaeger/issues/993
- https://github.com/opentracing/opentracing-java/issues/300

Which mentions: https://github.com/opentracing/opentracing-java/issues/300#issuecomment-720322903
> Any update on this?
> Unfortunately, no. Also, I don't think we'll make progress on this, given that work is now centered around OpenTelemetry.

So perhaps the way to go nowadays is with **https://opentelemetry.io/**
